DROP TABLE tb_as_analise CASCADE CONSTRAINTS;
DROP TABLE tb_as_local CASCADE CONSTRAINTS;
DROP TABLE tb_as_telefone CASCADE CONSTRAINTS;
DROP TABLE tb_as_usuario CASCADE CONSTRAINTS;
DROP TABLE tb_as_planta CASCADE CONSTRAINTS;
DROP TABLE tb_as_status CASCADE CONSTRAINTS;
DROP TABLE tb_as_auditoria CASCADE CONSTRAINTS;
